
package comp9322.assignment1;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.4
 * 2017-10-19T03:16:43.537+11:00
 * Generated source version: 3.0.4
 */

@WebFault(name = "ValidationFault", targetNamespace = "http://assignment1.comp9322")
public class ValidationFaultMsg extends Exception {
    
    private comp9322.assignment1.ServiceFaultType validationFault;

    public ValidationFaultMsg() {
        super();
    }
    
    public ValidationFaultMsg(String message) {
        super(message);
    }
    
    public ValidationFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public ValidationFaultMsg(String message, comp9322.assignment1.ServiceFaultType validationFault) {
        super(message);
        this.validationFault = validationFault;
    }

    public ValidationFaultMsg(String message, comp9322.assignment1.ServiceFaultType validationFault, Throwable cause) {
        super(message, cause);
        this.validationFault = validationFault;
    }

    public comp9322.assignment1.ServiceFaultType getFaultInfo() {
        return this.validationFault;
    }
}
