
package com.badbanana.poll.api;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EmployeeValidationService", targetNamespace = "http://assignment1.comp9322")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EmployeeValidationService {


    /**
     * 
     * @param parameters
     * @return
     *     returns com.badbanana.poll.api.CheckEmailAddressResponse
     */
    @WebMethod(operationName = "CheckEmailAddress", action = "http://assignment1.comp9322/CheckEmailAddress")
    @WebResult(name = "CheckEmailAddressResponse", targetNamespace = "http://assignment1.comp9322", partName = "parameters")
    public CheckEmailAddressResponse checkEmailAddress(
        @WebParam(name = "CheckEmailAddressRequest", targetNamespace = "http://assignment1.comp9322", partName = "parameters")
        CheckEmailAddressRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.badbanana.poll.api.CheckAddressResponse
     * @throws ValidationFaultMsg
     */
    @WebMethod(operationName = "CheckAddress", action = "http://assignment1.comp9322/CheckAddress")
    @WebResult(name = "CheckAddressResponse", targetNamespace = "http://assignment1.comp9322", partName = "parameters")
    public CheckAddressResponse checkAddress(
        @WebParam(name = "CheckAddressRequest", targetNamespace = "http://assignment1.comp9322", partName = "parameters")
        CheckAddressRequest parameters)
        throws ValidationFaultMsg
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns com.badbanana.poll.api.ReturnPostcodeResponse
     * @throws ValidationFaultMsg
     */
    @WebMethod(operationName = "ReturnPostcode", action = "http://assignment1.comp9322/ReturnPostcode")
    @WebResult(name = "ReturnPostcodeResponse", targetNamespace = "http://assignment1.comp9322", partName = "parameters")
    public ReturnPostcodeResponse returnPostcode(
        @WebParam(name = "ReturnPostcodeRequest", targetNamespace = "http://assignment1.comp9322", partName = "parameters")
        ReturnPostcodeRequest parameters)
        throws ValidationFaultMsg
    ;

}
