
package com.badbanana.poll.api;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "ValidationFault", targetNamespace = "http://assignment1.comp9322")
public class ValidationFaultMsg
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ServiceFaultType faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public ValidationFaultMsg(String message, ServiceFaultType faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public ValidationFaultMsg(String message, ServiceFaultType faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.badbanana.poll.api.ServiceFaultType
     */
    public ServiceFaultType getFaultInfo() {
        return faultInfo;
    }

}
